#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "hotfix" ] || [ "$current_branch" = "Hotfix/mejorasV_1_0" ]; then
  commit_msg=$(cat $1)
  if ! echo "$commit_msg" | grep -iq "^A corregir por:"; then
    echo "ERROR: El mensaje de commit debe comenzar con 'A corregir por:'"
    exit 1
  fi
fi