#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
 
if [ `git symbolic-ref --short HEAD` = "hotfix" ]
then
 if grep "A corregir por:" .git/COMMIT_EDITMSG
 then
   exit 0;
 else
     echo "El mensaje del commit no es valido, debe contener 'A corregir por:'";
     exit 1;
 fi
fi